/**
 * Layer 2 - Observation, in the Worker.
 *
 * Turns a Crop into an Observation with one Workers AI call. Everything this module knows
 * about the vision provider stops here: callers hand it a Crop and receive a validated
 * Observation or an `ObservationError`.
 *
 * Four details of the Workers AI API decide whether this works at all. Each is easy to get
 * wrong and each fails in a way that looks like something else.
 *
 * 1. **The image travels inside `messages[].content`**, as OpenAI-style content parts:
 *    `{ type: "image_url", image_url: { url: "data:image/jpeg;base64,..." } }` beside a
 *    `{ type: "text", text }` part. The top-level `image` parameter is deprecated.
 * 2. **`max_tokens` defaults to 256.** An Observation does not fit in 256 tokens, so the
 *    default truncates the JSON mid-object and the failure reads as a broken model rather
 *    than a missing parameter. It is always set explicitly here.
 * 3. **`guided_json` constrains decoding.** `llama-4-scout` is on Workers AI specifically
 *    because it documents this (SPEC.md, "Layer 2"); it is what lets TheFace skip custom
 *    JSON repair code.
 * 4. **The `Ai` binding arrives as a parameter.** This module never reads
 *    `cloudflare:workers` env, so the call is testable with a stub and the Worker keeps
 *    control of its own bindings.
 */

import { OBSERVATION_SYSTEM_PROMPT, OBSERVATION_USER_PROMPT } from "./prompt";
import { OBSERVATION_JSON_SCHEMA, ObservationSchema } from "./schema";
import type { Observation } from "./schema";

/**
 * The only Workers AI vision model that documents `guided_json`. See SPEC.md, "Layer 2":
 * the cheaper `llama-3.2-11b-vision-instruct` would save about $8 each month and cost us
 * custom JSON repair code.
 */
export const OBSERVATION_MODEL = "@cf/meta/llama-4-scout-17b-16e-instruct" as const;

/**
 * Explicit, because the API default of 256 truncates an Observation.
 *
 * The schema is roughly 40 short enum fields, which decode to about 500 tokens. 1024 leaves
 * headroom without inviting the model to write prose it has no field for.
 */
export const DEFAULT_MAX_TOKENS = 1024;

/** An Observation is a record of facts, so the sampling should be near-deterministic. The
 * model's own default is 0.15. */
export const DEFAULT_TEMPERATURE = 0.1;

const SUPPORTED_DATA_URL = /^data:image\/(?:jpeg|jpg|png|webp);base64,/i;

/* -------------------------------------------------------------------------------------- *
 * The vision binding
 * -------------------------------------------------------------------------------------- */

export type VisionContentPart =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string } };

export interface VisionMessage {
  role: "system" | "user";
  content: string | VisionContentPart[];
}

/** Exactly the request this module sends. There is no top-level `image` field: it is
 * deprecated, and leaving it out of the type makes re-adding it a compile error. */
export interface VisionRequest {
  messages: VisionMessage[];
  max_tokens: number;
  temperature: number;
  guided_json: object;
}

/**
 * The slice of the Workers AI `Ai` binding this module uses.
 *
 * Structural rather than the global `Ai` type for two reasons: `worker-configuration.d.ts`
 * is generated by `wrangler types` and is not in the repository, and a structural type lets
 * a test pass a stub instead of a real binding.
 *
 * `model` is typed as the literal this module sends, which is a key of Workers AI's own
 * model map, so a real `env.AI` matches. `input` is deliberately widened to `object`:
 * Workers AI's generated per-model input types have lagged the REST API on multimodal
 * content parts, and a narrow parameter here would turn that lag into a compile error at the
 * call site. {@link VisionRequest} is the real, exact request, and
 * {@link buildObservationRequest} is typed by it.
 */
export interface VisionBinding {
  run(model: typeof OBSERVATION_MODEL, input: object, options?: object): Promise<unknown>;
}

/* -------------------------------------------------------------------------------------- *
 * Failure
 * -------------------------------------------------------------------------------------- */

export type ObservationFailure =
  /** The Crop was empty or not a supported base64 image. */
  | "invalid_crop"
  /** The binding returned nothing usable. */
  | "empty_response"
  /** The response was not JSON. Usually truncation: check `max_tokens`. */
  | "malformed_json"
  /** The response was JSON but not an Observation. */
  | "schema_mismatch";

/** A failure to produce an Observation. The Worker turns this into a retry message; it never
 * shows a Visitor a partial Observation. */
export class ObservationError extends Error {
  readonly failure: ObservationFailure;

  constructor(failure: ObservationFailure, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "ObservationError";
    this.failure = failure;
  }
}

/* -------------------------------------------------------------------------------------- *
 * The call
 * -------------------------------------------------------------------------------------- */

export interface ObserveOptions {
  /** Defaults to {@link DEFAULT_MAX_TOKENS}. Never left to the API default of 256. */
  maxTokens?: number;
  /** Defaults to {@link DEFAULT_TEMPERATURE}. */
  temperature?: number;
}

/**
 * Builds the request sent to Workers AI.
 *
 * Exported so the request shape can be inspected without a call. `crop` is the Crop as
 * base64-encoded JPEG, with or without a `data:` URL prefix.
 */
export function buildObservationRequest(crop: string, options: ObserveOptions = {}): VisionRequest {
  return {
    messages: [
      { role: "system", content: OBSERVATION_SYSTEM_PROMPT },
      {
        role: "user",
        content: [
          { type: "text", text: OBSERVATION_USER_PROMPT },
          { type: "image_url", image_url: { url: toDataUrl(crop) } },
        ],
      },
    ],
    max_tokens: options.maxTokens ?? DEFAULT_MAX_TOKENS,
    temperature: options.temperature ?? DEFAULT_TEMPERATURE,
    guided_json: OBSERVATION_JSON_SCHEMA,
  };
}

/**
 * Observes a Crop.
 *
 * @param ai    The Workers AI binding, passed in by the caller.
 * @param crop  The Crop as base64-encoded JPEG, with or without a `data:` URL prefix.
 * @throws {ObservationError} when the model returns nothing that validates as an Observation.
 */
export async function observe(
  ai: VisionBinding,
  crop: string,
  options: ObserveOptions = {},
): Promise<Observation> {
  const request = buildObservationRequest(crop, options);
  const raw = await ai.run(OBSERVATION_MODEL, request);
  return parseObservation(raw, request.max_tokens);
}

/**
 * Validates what came back.
 *
 * Exported for the Worker's own error handling and for tests. `maxTokens` is used only to
 * write a useful message: truncation by `max_tokens` is the single most likely cause of
 * malformed JSON here, and it presents as a model failure until someone checks.
 */
export function parseObservation(
  raw: unknown,
  maxTokens: number = DEFAULT_MAX_TOKENS,
): Observation {
  const payload = extractPayload(raw);

  if (payload === undefined) {
    throw new ObservationError(
      "empty_response",
      "Workers AI returned no `response` field for the Observation.",
    );
  }

  let parsed: unknown;
  if (typeof payload === "string") {
    const text = payload.trim();
    if (text === "") {
      throw new ObservationError("empty_response", "Workers AI returned an empty Observation.");
    }
    try {
      parsed = JSON.parse(text);
    } catch (cause) {
      throw new ObservationError(
        "malformed_json",
        `The Observation was not valid JSON. The most likely cause is truncation: max_tokens was ${maxTokens}, and the Workers AI default of 256 is too small for an Observation.`,
        { cause },
      );
    }
  } else {
    // Workers AI sometimes hands back an already-parsed object under `response`.
    parsed = payload;
  }

  const result = ObservationSchema.safeParse(parsed);
  if (!result.success) {
    const fields = result.error.issues.map((issue) => issue.path.join(".")).join(", ");
    throw new ObservationError(
      "schema_mismatch",
      `The Observation did not match the schema. Fields at fault: ${fields}.`,
      { cause: result.error },
    );
  }

  return result.data;
}

/* -------------------------------------------------------------------------------------- *
 * Internals
 * -------------------------------------------------------------------------------------- */

/** Accepts a bare base64 Crop or a `data:` URL, and always produces a `data:` URL, because
 * that is what the `image_url` content part requires. */
function toDataUrl(crop: string): string {
  const trimmed = crop.trim();

  if (trimmed === "") {
    throw new ObservationError("invalid_crop", "The Crop was empty.");
  }
  if (SUPPORTED_DATA_URL.test(trimmed)) {
    return trimmed;
  }
  if (trimmed.startsWith("data:")) {
    throw new ObservationError(
      "invalid_crop",
      "The Crop must be a base64 JPEG, PNG or WebP data URL.",
    );
  }

  // A bare base64 payload. The Crop is encoded as JPEG in the browser (SPEC.md, "Layer 1").
  return `data:image/jpeg;base64,${trimmed}`;
}

/** Workers AI text generation returns `{ response, usage }`. Some paths return the string
 * alone. */
function extractPayload(raw: unknown): string | object | undefined {
  if (typeof raw === "string") {
    return raw;
  }
  if (raw !== null && typeof raw === "object" && "response" in raw) {
    const { response } = raw as { response: unknown };
    if (typeof response === "string" || (typeof response === "object" && response !== null)) {
      return response;
    }
  }
  return undefined;
}
