/**
 * The Roster, generated by `pnpm celebs:score` and committed as `roster.json`.
 *
 * SERVER ONLY. Every entry carries its Celebrity's raw Overall, and a client import would
 * ship all of them to every browser (ADR-0009). The Compliment that leaves the server carries
 * a name, a photo and a credit, never a number.
 *
 * Parsed lazily and once, so a broken file costs the Compliment, not the module that imports
 * it: `scoreCrop` catches the throw and scores without a pop-up.
 */
import rosterJson from "./roster.json";
import { RosterSchema, type Celebrity } from "./schema";

let roster: readonly Celebrity[] | undefined;

export function loadRoster(): readonly Celebrity[] {
  roster ??= RosterSchema.parse(rosterJson);
  return roster;
}
